-- Remove trigger/função se já existirem
DROP TRIGGER IF EXISTS TG_AntesDeInserirInscricao ON TB_Inscricao;
DROP FUNCTION IF EXISTS FC_VerificarInscricaoAtividade();

-- TABELA USUARIO
CREATE TABLE TB_Usuario (
    ID_Usuario INTEGER GENERATED ALWAYS AS IDENTITY,
    CD_CPF VARCHAR,
    DS_Email VARCHAR,
	DS_Senha VARCHAR,
    DS_Nome VARCHAR,
    DS_Instituicao VARCHAR,
    DS_Escolaridade VARCHAR
);
-- PRIMARY KEY
ALTER TABLE TB_Usuario ADD CONSTRAINT PK_Usuario PRIMARY KEY (ID_Usuario);

-- TABELA REGISTRO
CREATE TABLE TB_Registro (
	ID_Registro INTEGER GENERATED ALWAYS AS IDENTITY,
	ID_EventoPai INTEGER,
	TP_Registro VARCHAR,
	DS_Titulo VARCHAR,
	DS_Descricao VARCHAR,
	VL_ValorEvento DECIMAL,
	DS_Local VARCHAR,
	DH_Inicio TIMESTAMP,
	DH_Fim TIMESTAMP,
	TP_Area VARCHAR
);
-- PRIMARY KEY
ALTER TABLE TB_Registro ADD CONSTRAINT PK_Registro PRIMARY KEY (ID_Registro);

-- TABELA INSCRICAO
CREATE TABLE TB_Inscricao (
	ID_Inscricao INTEGER GENERATED ALWAYS AS IDENTITY,
	ID_Registro INTEGER,
	ID_Usuario INTEGER,
	DH_DataInscricao TIMESTAMP,
	TP_Inscricao VARCHAR,
    ST_Pagamento VARCHAR,
	VL_CustoInscricao DECIMAL,
	ST_Presente BOOLEAN
);
-- PRIMARY KEY
ALTER TABLE TB_Inscricao ADD CONSTRAINT PK_Inscricao PRIMARY KEY (ID_Inscricao);

-- TABELA PAGAMENTO
CREATE TABLE TB_Pagamento (
    ID_Pagamento INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Inscricao INTEGER,
    DH_DataPagamento TIMESTAMP,
    VL_ValorPago DECIMAL,
    TP_MetodoPagamento VARCHAR,
    CD_Transacao VARCHAR
);
-- PRIMARY KEY
ALTER TABLE TB_Pagamento ADD CONSTRAINT PK_Pagamento PRIMARY KEY (ID_Pagamento);

-- TABELA CERTIFICADO
CREATE TABLE TB_Certificado (
    ID_Certificado INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Inscricao INTEGER,
    CD_Validacao VARCHAR,
    DH_Emissao TIMESTAMP
);
-- PRIMARY KEY
ALTER TABLE TB_Certificado ADD CONSTRAINT PK_Certificado PRIMARY KEY (ID_Certificado);

-- TABELA RECUPERACAO SENHA
CREATE TABLE TB_RecuperacaoSenha (
    ID_Recuperacao INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Usuario INTEGER,
    CD_Token VARCHAR(32),
    DH_Solicitacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ST_Usado BOOLEAN DEFAULT FALSE
);
-- PRIMARY KEY
ALTER TABLE TB_RecuperacaoSenha ADD CONSTRAINT PK_RecuperacaoSenha PRIMARY KEY (ID_Recuperacao);

-- TABELA AUDITORIA CANCELAMENTO INSCRICAO
CREATE TABLE TB_AuditoriaCancelamento (
    ID_Log INTEGER GENERATED ALWAYS AS IDENTITY,
    ID_Inscricao INTEGER NOT NULL,
    DH_Acao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DS_Motivo VARCHAR(255)
);
-- PRIMARY KEY
ALTER TABLE TB_AuditoriaCancelamento ADD CONSTRAINT PK_AuditoriaCancelamento PRIMARY KEY (ID_Log);

-- DEFINIÇÃO DAS CONSTRAINTS
-- UNIQUE KEY USUARIO/CPF
ALTER TABLE TB_Usuario ADD CONSTRAINT UK_Usuario_CPF UNIQUE (CD_CPF);
-- UNIQUE KEY USUARIO/EMAIL
ALTER TABLE TB_Usuario ADD CONSTRAINT UK_Usuario_Email UNIQUE (DS_Email);

-- FOREIGN KEY ATIVIDADE/EVENTO
ALTER TABLE TB_Registro ADD CONSTRAINT FK_Registro_EventoPai
    FOREIGN KEY (ID_EventoPai)
    REFERENCES TB_Registro (ID_Registro);
	
-- UNIQUE KEY INSCRICAO (USUARIO,REGISTRO)
ALTER TABLE TB_Inscricao ADD CONSTRAINT UK_Usuario_Registro UNIQUE (ID_Registro, ID_Usuario);
-- FOREIGN KEY INSCRICAO_USUARIO
ALTER TABLE TB_Inscricao ADD CONSTRAINT FK_Inscricao_Usuario
    FOREIGN KEY (ID_Usuario)
    REFERENCES TB_Usuario (ID_Usuario);
-- FOREIGN KEY INSCRICAO_REGISTRO
ALTER TABLE TB_Inscricao ADD CONSTRAINT FK_Inscricao_Registro
    FOREIGN KEY (ID_Registro)
    REFERENCES TB_Registro (ID_Registro);
	
-- FOREIGN KEY PAGAMENTO/INSCRICAO
ALTER TABLE TB_Pagamento ADD CONSTRAINT FK_Pagamento_Inscricao
    FOREIGN KEY (ID_Inscricao)
    REFERENCES TB_Inscricao (ID_Inscricao);
	
-- FOREIGN KEY CERTIFICADO/INSCRICAO
ALTER TABLE TB_Certificado ADD CONSTRAINT FK_Certificado_Inscricao
    FOREIGN KEY (ID_Inscricao)
    REFERENCES TB_Inscricao (ID_Inscricao);

-- FOREIGN KEY RECUPERACAO_SENHA/USUARIO
ALTER TABLE TB_RecuperacaoSenha ADD CONSTRAINT FK_RecuperacaoSenha_Usuario
    FOREIGN KEY (ID_Usuario)
    REFERENCES TB_Usuario (ID_Usuario);

-- FOREIGN KEY AUDITORIA_CANCELAMENTO/INSCRICAO
ALTER TABLE TB_AuditoriaCancelamento ADD CONSTRAINT FK_AuditoriaCancelamento_Inscricao
    FOREIGN KEY (ID_Inscricao)
    REFERENCES TB_Inscricao (ID_Inscricao);